[profile.default]
solc_version = '0.8.15'
auto_detect_solc = false
optimizer_runs = 10000

src = 'contracts/src/v0.8/ccip'
test = 'contracts/src/v0.8/ccip/test'
out = 'contracts/foundry-artifacts'
libs = ["contracts/node_modules", "lib"]

gas_price = 1

# See more config options https://github.com/foundry-rs/foundry/tree/master/config