ChainID = '1111'
ChainType = 'wemix'
FinalityDepth = 1
MinIncomingConfirmations = 1
# WeMix emits a block every 1 second, regardless of transactions
LogPollInterval = '3s'
NoNewHeadsThreshold = '30s'
RPCBlockQueryDelay = 10

[OCR]
ContractConfirmations = 1

[GasEstimator]
EIP1559DynamicFees = true
PriceMin = '1 mwei'
TipCapDefault = '100 gwei'
