name: CCIP Contract Tests
on: [pull_request]

env:
  FOUNDRY_PROFILE: ci

jobs:
  solhint:
    name: Solhint
    runs-on: ubuntu-20.04

    steps:
      - name: Collect Metrics
        id: collect-gha-metrics
        uses: smartcontractkit/push-gha-metrics-action@v1
        with:
          basic-auth: ${{ secrets.GRAFANA_CLOUD_BASIC_AUTH }}
          hostname: ${{ secrets.GRAFANA_CLOUD_HOST }}
          this-job-name: Solhint
        continue-on-error: true
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - name: Run Solhint
        run: |
          cd ./contracts/
          yarn lint:ccip

  foundry:
    name: Foundry Test
    runs-on: ubuntu-20.04

    steps:
      - name: Collect Metrics
        id: collect-gha-metrics
        uses: smartcontractkit/push-gha-metrics-action@v1
        with:
          basic-auth: ${{ secrets.GRAFANA_CLOUD_BASIC_AUTH }}
          hostname: ${{ secrets.GRAFANA_CLOUD_HOST }}
          this-job-name: Foundry Test
        continue-on-error: true

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

      - name: Check gas snapshots
        run: |
          forge snapshot --check
        id: gas-check
