name: CCIP Contracts
on: [pull_request]

env:
  FOUNDRY_PROFILE: ci

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.src }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - uses: dorny/paths-filter@b2feaf19c27470162a626bd6fa8438ae5b263721 # v2.10.2
        id: changes
        with:
          filters: |
            src:
              - 'contracts/**/*'
              - '.github/workflows/ccip-contracts.yml'

  solhint:
    needs: [changes]
    name: Solhint
    runs-on: ubuntu-latest

    steps:
      - name: Collect Metrics
        if: ${{ needs.changes.outputs.changes == 'true' }}
        id: collect-gha-metrics
        uses: smartcontractkit/push-gha-metrics-action@v1
        with:
          basic-auth: ${{ secrets.GRAFANA_CLOUD_BASIC_AUTH }}
          hostname: ${{ secrets.GRAFANA_CLOUD_HOST }}
          this-job-name: Solhint
        continue-on-error: true
      - name: Checkout the repo
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - name: Setup NodeJS
        if: ${{ needs.changes.outputs.changes == 'true' }}
        uses: ./.github/actions/setup-nodejs
      - name: Run Solhint
        if: ${{ needs.changes.outputs.changes == 'true' }}
        working-directory: contracts
        run: pnpm lint:ccip

  coverage:
    needs: [changes]
    name: Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Collect Metrics
        if: ${{ needs.changes.outputs.changes == 'true' }}
        id: collect-gha-metrics
        uses: smartcontractkit/push-gha-metrics-action@v1
        with:
          basic-auth: ${{ secrets.GRAFANA_CLOUD_BASIC_AUTH }}
          hostname: ${{ secrets.GRAFANA_CLOUD_HOST }}
          this-job-name: Coverage
        continue-on-error: true

      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          submodules: recursive

      - name: Install Foundry
        if: ${{ needs.changes.outputs.changes == 'true' }}
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        if: ${{ needs.changes.outputs.changes == 'true' }}
        run: |
          forge --version
          forge build
        id: build
      
      - name: Run coverage
        if: ${{ needs.changes.outputs.changes == 'true' }}
        run: forge coverage --report lcov

      - name: Prune report
        if: ${{ needs.changes.outputs.changes == 'true' }}
        run: |
          sudo apt-get install lcov
          ./tools/ci/ccip_lcov_prune ./lcov.info ./lcov.info.pruned

      - name: Report code coverage
        if: ${{ needs.changes.outputs.changes == 'true' }}
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: lcov.info.pruned
          minimum-coverage: 77
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Collect Metrics
        id: collect-gha-metrics
        uses: smartcontractkit/push-gha-metrics-action@v1
        with:
          basic-auth: ${{ secrets.GRAFANA_CLOUD_BASIC_AUTH }}
          hostname: ${{ secrets.GRAFANA_CLOUD_HOST }}
          this-job-name: Tests
        continue-on-error: true

      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge snapshot -vvv --check
        id: test

  abi:
    needs: [changes]
    name: ABI
    runs-on: ubuntu-latest

    steps:
      - name: Collect Metrics
        if: ${{ needs.changes.outputs.changes == 'true' }}
        id: collect-gha-metrics
        uses: smartcontractkit/push-gha-metrics-action@v1
        with:
          basic-auth: ${{ secrets.GRAFANA_CLOUD_BASIC_AUTH }}
          hostname: ${{ secrets.GRAFANA_CLOUD_HOST }}
          this-job-name: ABI
        continue-on-error: true

      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          submodules: recursive

      - name: Install Foundry
        if: ${{ needs.changes.outputs.changes == 'true' }}
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        if: ${{ needs.changes.outputs.changes == 'true' }}
        run: |
          forge --version
          forge build
        id: build

      - name: Check Public ABIs
        if: ${{ needs.changes.outputs.changes == 'true' }}
        run: |
          ./tools/ci/ccip_public_abi_check
        id: abi-check
